import Link from "next/link";
import { Gem } from "lucide-react";

export const metadata = {
  title: "Terms of Service - Opcify",
};

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-8 sm:py-16">
      {/* Header */}
      <div className="mb-10">
        <Link href="/" className="inline-flex items-center gap-1.5 text-muted transition-colors hover:text-secondary">
          <Gem className="h-5 w-5 text-emerald-400" />
          <span className="text-lg font-bold tracking-tight text-primary">Opcify</span>
        </Link>
      </div>

      <h1 className="text-3xl font-bold tracking-tight text-primary">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted">Last updated: March 27, 2026</p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-secondary">
        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the Opcify AI Workspace Platform (the &quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">2. Description of Service</h2>
          <p>
            Opcify provides an AI workforce management platform that allows users to create workspaces, configure AI agents, manage tasks, and automate workflows. The Service includes web applications, APIs, and related tools and documentation.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">3. Account Registration</h2>
          <ul className="list-disc space-y-1.5 pl-5">
            <li>You must provide accurate and complete information when creating an account.</li>
            <li>You are responsible for maintaining the confidentiality of your credentials.</li>
            <li>You are responsible for all activities that occur under your account.</li>
            <li>You must notify us immediately of any unauthorized use of your account.</li>
            <li>You must be at least 16 years old to create an account.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">4. Acceptable Use</h2>
          <p className="mb-3">You agree not to use the Service to:</p>
          <ul className="list-disc space-y-1.5 pl-5">
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe upon the rights of others</li>
            <li>Generate, distribute, or store harmful, illegal, or offensive content</li>
            <li>Attempt to gain unauthorized access to the Service or its systems</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
            <li>Use the Service for competitive analysis or to build a competing product</li>
            <li>Circumvent any usage limits, rate limits, or access controls</li>
            <li>Use AI agents to impersonate real individuals without consent</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">5. AI Agents and Content</h2>
          <h3 className="mb-2 font-medium text-primary">5.1 AI-Generated Content</h3>
          <p className="mb-3">
            Content generated by AI agents through the Service is provided &quot;as is.&quot; You are responsible for reviewing, verifying, and approving all AI-generated content before use. We do not guarantee the accuracy, completeness, or suitability of AI outputs.
          </p>
          <h3 className="mb-2 font-medium text-primary">5.2 Your Content</h3>
          <p>
            You retain ownership of content you provide to the Service. By using the Service, you grant us a limited license to process your content as necessary to operate the platform, including sending it to AI model providers for task execution.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">6. Intellectual Property</h2>
          <p>
            The Service, including its design, features, code, and documentation, is owned by Opcify and protected by intellectual property laws. These Terms do not grant you any right to use Opcify trademarks, logos, or brand features without prior written consent.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">7. Payment and Billing</h2>
          <ul className="list-disc space-y-1.5 pl-5">
            <li>Certain features of the Service may require a paid subscription.</li>
            <li>Fees are billed in advance on a monthly or annual basis.</li>
            <li>All fees are non-refundable unless otherwise stated.</li>
            <li>We reserve the right to modify pricing with 30 days&apos; notice.</li>
            <li>Failure to pay may result in suspension or termination of your account.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">8. Service Availability</h2>
          <p>
            We strive to maintain high availability but do not guarantee uninterrupted access to the Service. We may perform scheduled maintenance, updates, or modifications that temporarily affect availability. We will provide reasonable notice of planned downtime when possible.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Opcify shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising out of or related to your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">10. Disclaimer of Warranties</h2>
          <p>
            The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that AI agents will produce accurate or error-free results.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">11. Termination</h2>
          <p>
            Either party may terminate these Terms at any time. You may terminate by deleting your account. We may suspend or terminate your access if you violate these Terms or for any other reason with reasonable notice. Upon termination, your right to use the Service ceases immediately. We will make your data available for export for 30 days following termination.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">12. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Opcify is incorporated, without regard to conflict of law principles. Any disputes arising from these Terms shall be resolved through binding arbitration.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">13. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms and updating the &quot;Last updated&quot; date. Continued use of the Service after changes constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-primary">14. Contact Us</h2>
          <p>
            If you have questions about these Terms, please contact us at{" "}
            <a href="mailto:legal@opcify.com" className="text-emerald-500 hover:text-emerald-400">
              legal@opcify.com
            </a>.
          </p>
        </section>
      </div>

      {/* Footer */}
      <div className="mt-12 border-t border-border-muted pt-6 text-xs text-muted">
        <div className="flex items-center gap-4">
          <Link href="/privacy" className="transition-colors hover:text-secondary">Privacy Policy</Link>
          <span className="text-border-muted">|</span>
          <Link href="/login" className="transition-colors hover:text-secondary">Back to Login</Link>
        </div>
      </div>
    </div>
  );
}
