version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "4210:4210"
    environment:
      - DATABASE_URL=file:./opcify.db
      - API_PORT=4210
      - API_HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "3210:3210"
    depends_on:
      - api

volumes:
  redis-data:
